version: "3.8"

volumes:
  mongo-data: {}

networks:
  elk:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./env/.env.shared
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend-app
    env_file:
      - ./env/.env.shared
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mongodb
    networks:
      - default
      - elk

  frontend:
    build: ./frontend
    container_name: frontend-app
    env_file:
      - ./env/.env.shared
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - default
      - elk