services:
  backend:
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - ./env/.env.dev

  frontend:
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - ./env/.env.dev
