version: "3.8"

services:
  # -------------------- App stack --------------------
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend-app
    env_file:
      - ./.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend-app
    env_file:
      - ./.env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - backend

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
      container_name: elasticsearch
      environment:
        - node.name=elasticsearch
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - xpack.security.enabled=false
        - xpack.security.audit.enabled=true
  #     - ELASTIC_PASSWORD=elastic_password123 # Change this password
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      networks:
        - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #    - ELASTICSEARCH_USERNAME=elastic
  #    - ELASTICSEARCH_PASSWORD=elastic_password123 # Same as Elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  mongo-data:
  elasticsearch-data:
    driver: local

networks:
  elk:
    driver: bridge