services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend 
    container_name: backend-app
    env_file:
      - ./.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src/app # Mount host's ./backend to container's /usr/src/app for hot-reloading
      - /usr/src/app/node_modules # Do not mount the node_modules from the host
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - mongodb

  frontend:
    build: ./frontend 
    container_name: frontend-app
    env_file:
      - ./.env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - backend

volumes:
  mongo-data: